/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.CalculatriceStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CalculatriceStandaloneSetup extends CalculatriceStandaloneSetupGenerated {
  public static void doSetup() {
    CalculatriceStandaloneSetup _calculatriceStandaloneSetup = new CalculatriceStandaloneSetup();
    _calculatriceStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
