/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl.calculatrice;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.calculatrice.Boolean#getBoolValue <em>Bool Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.calculatrice.CalculatricePackage#getBoolean()
 * @model
 * @generated
 */
public interface Boolean extends BoolExpr
{
  /**
   * Returns the value of the '<em><b>Bool Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bool Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bool Value</em>' attribute.
   * @see #setBoolValue(String)
   * @see org.xtext.example.mydsl.calculatrice.CalculatricePackage#getBoolean_BoolValue()
   * @model
   * @generated
   */
  String getBoolValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.calculatrice.Boolean#getBoolValue <em>Bool Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bool Value</em>' attribute.
   * @see #getBoolValue()
   * @generated
   */
  void setBoolValue(String value);

} // Boolean
