/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl.calculatrice;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Calc</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.calculatrice.Calc#getBoolName <em>Bool Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.calculatrice.Calc#getB <em>B</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.calculatrice.Calc#isDecl <em>Decl</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.calculatrice.Calc#getVarName <em>Var Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.calculatrice.Calc#getE <em>E</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.calculatrice.CalculatricePackage#getCalc()
 * @model
 * @generated
 */
public interface Calc extends EObject
{
  /**
   * Returns the value of the '<em><b>Bool Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bool Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bool Name</em>' attribute.
   * @see #setBoolName(String)
   * @see org.xtext.example.mydsl.calculatrice.CalculatricePackage#getCalc_BoolName()
   * @model
   * @generated
   */
  String getBoolName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.calculatrice.Calc#getBoolName <em>Bool Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bool Name</em>' attribute.
   * @see #getBoolName()
   * @generated
   */
  void setBoolName(String value);

  /**
   * Returns the value of the '<em><b>B</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>B</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>B</em>' containment reference.
   * @see #setB(BoolExpr)
   * @see org.xtext.example.mydsl.calculatrice.CalculatricePackage#getCalc_B()
   * @model containment="true"
   * @generated
   */
  BoolExpr getB();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.calculatrice.Calc#getB <em>B</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>B</em>' containment reference.
   * @see #getB()
   * @generated
   */
  void setB(BoolExpr value);

  /**
   * Returns the value of the '<em><b>Decl</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Decl</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decl</em>' attribute.
   * @see #setDecl(boolean)
   * @see org.xtext.example.mydsl.calculatrice.CalculatricePackage#getCalc_Decl()
   * @model
   * @generated
   */
  boolean isDecl();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.calculatrice.Calc#isDecl <em>Decl</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Decl</em>' attribute.
   * @see #isDecl()
   * @generated
   */
  void setDecl(boolean value);

  /**
   * Returns the value of the '<em><b>Var Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Name</em>' attribute.
   * @see #setVarName(String)
   * @see org.xtext.example.mydsl.calculatrice.CalculatricePackage#getCalc_VarName()
   * @model
   * @generated
   */
  String getVarName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.calculatrice.Calc#getVarName <em>Var Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Name</em>' attribute.
   * @see #getVarName()
   * @generated
   */
  void setVarName(String value);

  /**
   * Returns the value of the '<em><b>E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>E</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>E</em>' containment reference.
   * @see #setE(CalcExpr)
   * @see org.xtext.example.mydsl.calculatrice.CalculatricePackage#getCalc_E()
   * @model containment="true"
   * @generated
   */
  CalcExpr getE();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.calculatrice.Calc#getE <em>E</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>E</em>' containment reference.
   * @see #getE()
   * @generated
   */
  void setE(CalcExpr value);

} // Calc
