/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl.calculatrice;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Calculatrice</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.calculatrice.Calculatrice#getCalculs <em>Calculs</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.calculatrice.CalculatricePackage#getCalculatrice()
 * @model
 * @generated
 */
public interface Calculatrice extends EObject
{
  /**
   * Returns the value of the '<em><b>Calculs</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.calculatrice.Calc}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Calculs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Calculs</em>' containment reference list.
   * @see org.xtext.example.mydsl.calculatrice.CalculatricePackage#getCalculatrice_Calculs()
   * @model containment="true"
   * @generated
   */
  EList<Calc> getCalculs();

} // Calculatrice
