/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl.calculatrice;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.calculatrice.CalculatricePackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends Calc
{
} // Condition
