/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl.calculatrice;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.calculatrice.VarCall#getVarCall <em>Var Call</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.calculatrice.CalculatricePackage#getVarCall()
 * @model
 * @generated
 */
public interface VarCall extends CalcExpr
{
  /**
   * Returns the value of the '<em><b>Var Call</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var Call</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Call</em>' attribute.
   * @see #setVarCall(String)
   * @see org.xtext.example.mydsl.calculatrice.CalculatricePackage#getVarCall_VarCall()
   * @model
   * @generated
   */
  String getVarCall();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.calculatrice.VarCall#getVarCall <em>Var Call</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Call</em>' attribute.
   * @see #getVarCall()
   * @generated
   */
  void setVarCall(String value);

} // VarCall
