/*
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.calculatrice.ui.internal.CalculatriceActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CalculatriceExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CalculatriceActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CalculatriceActivator.getInstance().getInjector(CalculatriceActivator.ORG_XTEXT_EXAMPLE_MYDSL_CALCULATRICE);
	}
	
}
