grammar org.xtext.example.mydsl.Calculatrice with org.eclipse.xtext.common.Terminals

generate calculatrice "http://www.xtext.org/example/mydsl/Calculatrice"

Model:
	formule+=Formule
;

Formule:
	Terme Operation
;

Operation:
	(('+'|'-') Terme Operation)?
;

OperationPrio:
	(('*'|'/') Facteur OperationPrio)?
;

Terme:
	Facteur OperationPrio
;

Facteur:
	'(' Formule ')'
	| Entier
;
	
	
terminal Entier:
	('-')?INT
	;
	
