/*
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CalculatriceStandaloneSetup extends CalculatriceStandaloneSetupGenerated {

	def static void doSetup() {
		new CalculatriceStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
